#ifndef CC3K_SAVEGAME_H
#define CC3K_SAVEGAME_H

#include <cstdint>
#include <optional>
#include <string>

namespace cc3k {

// Snapshot of a PlayerCharacter's mutable cross-floor state.
// Kept as plain integers/doubles to decouple SaveGame from Player.h.
struct PlayerSnapshot {
    int race = 0;          // static_cast<int>(Race)
    int maxHp = 140;
    int hp = 140;
    int atk = 20;
    int def = 20;
    int gold = 0;
    int score = 0;
    double goldModifier = 1.0;
    bool hasBarrierSuit = false;
    int visibility = 100;
    int movementSpeed = 1;
};

// A complete save record. Floor grid / enemies / items are intentionally
// not serialized: on load they are regenerated by replaying nextFloor()
// from a freshly seeded PRNG. This keeps the format small and stable.
struct SaveData {
    int version = 1;
    std::uint32_t seed = 1;
    std::string filename = "./files/default.txt";
    bool weatherEnabled = false;
    bool questEnabled = false;
    int floorId = 0;          // 0-based floor index at save time
    PlayerSnapshot player;
};

// JSON round-trip via a string. Pure functions, no I/O — easy to unit-test.
std::string toJson(const SaveData& d);
std::optional<SaveData> fromJson(const std::string& json);

// Filesystem wrappers. Return false / nullopt on any error.
bool save(const std::string& path, const SaveData& d);
std::optional<SaveData> load(const std::string& path);

} // namespace cc3k

#endif
